spring.application.name=catalog-service
rawg.api-key=${RAWG_API_KEY}
rawg.base-url=https://api.rawg.io/api
server.port=8082
spring.cloud.openfeign.circuitbreaker.group.enabled=true
logging.level.com.catalogservice=DEBUG